-- DELETE FROM appUser;
--
-- INSERT INTO appUser (id, email, password)
-- VALUES (1, 'admin_1@gmail.com', 'admin'),
--        (2, 'admin_2@gmail.com', 'admin'),
--        (3, 'john@yandex.ru', 'jpass'),
--        (4, 'paul@yandex.ru', 'ppass'),
--        (5, 'george@yandex.ru', 'gpass'),
--        (6, 'appUser@yandex.ru', 'upass');